version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/web-ui"
    schedule:
      interval: "weekly"
    security-updates-only: true

  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"
    security-updates-only: true

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    security-updates-only: true

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    security-updates-only: true
