services:
  chatbot:
    build:
      context: .
      args:
        - VITE_AGENT_API_BASE=${VITE_AGENT_API_BASE}
    container_name: igorekchatbot
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    networks:
      - mcpnet
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
      - MCP_URL=${MCP_URL}
      - VITE_MCP_URL=${VITE_MCP_URL}
      - VITE_AUTH_TOKEN=${VITE_AUTH_TOKEN}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
      - VITE_AGENT_API_BASE=http://chatbot:3000
    # Порты наружу не нужны, если через Caddy
    # ports:
    #   - "3000:3000"
  sandbox_executor:
    build:
      context: ./sandbox_executor
    container_name: sandbox_executor
    restart: unless-stopped
    networks:
      - mcpnet
    mem_limit: 128m
    cpus: 0.5

  browser:
    build:
      context: ./browser
    container_name: browser
    restart: unless-stopped
    networks:
      - mcpnet
    mem_limit: 512m
    cpus: 1.5
networks:
  mcpnet:
    external: true
