FROM node:20-slim

WORKDIR /app



RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*



COPY package*.json ./
RUN npm install --only=production
COPY server.js vaultAccess.js ./
EXPOSE 3333
CMD ["node", "server.js"]
